{{- if .Values.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Release.Name }}-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - {{ .Values.certificate.dnsName }}
---
apiVersion: apisix.apache.org/v2
kind: ApisixTls
metadata:
  name: {{ .Release.Name }}-tls
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: apisix
  hosts:
    - {{ .Values.certificate.dnsName }}
  secret:
    name: {{ .Release.Name }}-tls
    namespace: {{ .Release.Namespace }}
{{- end }}