name: Build and Deploy Application

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DOCKER_USERNAME: homosapiensother
  AWS_ROLE_ARN: arn:aws:iam::125832268136:role/aws-service-role/ecs.amazonaws.com/AWSServiceRoleForECS
  AWS_REGION: us-east-1
  TASK_DEFINITION: pulumi-dev-task-definition-nginx
  CONTAINER_NAME: pulumi-dev-nginx
  ECS_SERVICE: pulumi-dev-service
  ECS_CLUSTER: pulumi-dev-cluster-0ad512a

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push-docker-image:
    name: Build and Push to DockerHub
    runs-on: ubuntu-24.04
    outputs:
      image-tag: ${{ steps.meta.outputs.image-tag }}
      image-uri: ${{ steps.push.outputs.image-uri }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: homosapiensother/solivar-blog
        tags: |
          type=raw,value=${{ github.ref_name }}-${{ github.run_number }}

    - name: Build and push Docker image
      id: push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

  # update-ecs-service:
  #   name: Update ECS Service
  #   runs-on: ubuntu-24.04
  #   needs: [ build-and-push-docker-image ]

  #   steps:
  #   - name: Configure AWS credentials
  #     uses: aws-actions/configure-aws-credentials@v4
  #     with:
  #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #       aws-region: ${{ env.AWS_REGION }}

  #   - name: Download current task definition
  #     run: |
  #       aws ecs describe-task-definition \
  #         --task-definition ${{ env.TASK_DEFINITION }} \
  #         --query taskDefinition > task-definition.json

  #   - name: Update task definition with new image
  #     id: task-def
  #     uses: aws-actions/amazon-ecs-render-task-definition@v1
  #     with:
  #       task-definition: task-definition.json
  #       container-name: ${{ env.CONTAINER_NAME }}
  #       image: ${{ needs.build-and-push-docker-image.outputs.image-uri }}

  #   - name: Deploy to Amazon ECS service
  #     uses: aws-actions/amazon-ecs-deploy-task-definition@v2
  #     with:
  #       task-definition: ${{ steps.task-def.outputs.task-definition }}
  #       service: ${{ env.ECS_SERVICE }}
  #       cluster: ${{ env.ECS_CLUSTER }}
  #       wait-for-service-stability: true